services:
    ibexa.api_platform.action.entrypoint:
        parent: api_platform.action.entrypoint
        arguments:
            index_0: '@Ibexa\Bundle\Rest\ApiPlatform\ClassNameResourceNameCollectionFactory'
            index_1: '@ibexa.api_platform.state_provider.documentation.content_negotiation'

    ibexa.api_platform.state_provider.documentation.content_negotiation:
        parent: api_platform.state_provider.documentation.content_negotiation
        arguments:
            index_0: '@ibexa.api_platform.swagger_ui.documentation.provider'

    ibexa.api_platform.swagger_ui.documentation.provider:
        parent: api_platform.swagger_ui.documentation.provider
        arguments:
            index_1: '@ibexa.api_platform.ibexa_openapi.factory'

    ibexa.api_platform.ibexa_openapi.factory:
        class: 'Ibexa\Bundle\Rest\ApiPlatform\OpenApiFactory'
        decorates: ibexa.api_platform.openapi.factory
        arguments:
            - '@.inner'
            - '@Ibexa\Bundle\Rest\ApiPlatform\SchemasCollectionFactory'
            - '@Symfony\Component\HttpKernel\KernelInterface'

    ibexa.api_platform.openapi.factory:
        parent: api_platform.openapi.factory
        arguments:
            index_0: '@Ibexa\Bundle\Rest\ApiPlatform\ClassNameResourceNameCollectionFactory'

    Ibexa\Bundle\Rest\ApiPlatform\ClassNameResourceNameCollectionFactory: ~


    # Collecting schemas

    Ibexa\Bundle\Rest\ApiPlatform\SchemasCollectionFactory: ~

    ibexa.api_platform.schemas_provider.rest:
        class: Ibexa\Rest\ApiPlatform\SchemasProvider
        autowire: true
        autoconfigure: true
        arguments:
            $files:
                - '@@IbexaRestBundle/Resources/api_platform/base_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/bookmarks_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/content_locations_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/content_objects_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/content_sections_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/content_trash_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/content_type_groups_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/content_types_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/content_url_aliases_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/content_url_wildcards_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/language_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/object_state_groups_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/services_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/views_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/user/roles_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/user/sessions_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/user/token_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/user/user_groups_schemas.yml'
                - '@@IbexaRestBundle/Resources/api_platform/user/users_schemas.yml'
