services:
    Ibexa\Rest\Server\Input\Parser\ContentType\Criterion\CriterionProcessor:
        parent: Ibexa\Contracts\Rest\Input\Parser\Query\Criterion\BaseCriterionProcessor

    Ibexa\Rest\Server\Input\Parser\ContentType\SortClause\SortClauseProcessor:
        parent: Ibexa\Contracts\Rest\Input\Parser\Query\SortClause\BaseSortClauseProcessor

    _instanceof:
        Ibexa\Rest\Server\Input\Parser\ContentType\Criterion\ContentTypeCriterionInterface:
            tags:
                - 'ibexa.rest.content_type.criterion'

    Ibexa\Rest\Server\Input\Parser\ContentType\Criterion\ContentTypeCriteriaRegistry:
        arguments:
            - !tagged_iterator ibexa.rest.content_type.criterion

    Ibexa\Rest\Server\Input\Parser\ContentType\Criterion\ContentTypeId:
        parent: Ibexa\Rest\Server\Common\Parser
        tags:
            - { name: ibexa.rest.input.parser, mediaType: application/vnd.ibexa.api.internal.criterion.ContentTypeId }

    Ibexa\Rest\Server\Input\Parser\ContentType\Criterion\ContentTypeIdentifier:
        parent: Ibexa\Rest\Server\Common\Parser
        tags:
            - { name: ibexa.rest.input.parser, mediaType: application/vnd.ibexa.api.internal.criterion.ContentTypeIdentifier }

    Ibexa\Rest\Server\Input\Parser\ContentType\Criterion\IsSystem:
        parent: Ibexa\Rest\Server\Common\Parser
        tags:
            - { name: ibexa.rest.input.parser, mediaType: application/vnd.ibexa.api.internal.criterion.IsSystem }

    Ibexa\Rest\Server\Input\Parser\ContentType\Criterion\ContentTypeGroupId:
        parent: Ibexa\Rest\Server\Common\Parser
        tags:
            - { name: ibexa.rest.input.parser, mediaType: application/vnd.ibexa.api.internal.criterion.ContentTypeGroupId }

    Ibexa\Rest\Server\Input\Parser\ContentType\Criterion\ContainsFieldDefinitionId:
        parent: Ibexa\Rest\Server\Common\Parser
        tags:
            - { name: ibexa.rest.input.parser, mediaType: application/vnd.ibexa.api.internal.criterion.ContainsFieldDefinitionId }
