parameters:
services:
    # Following service will be aliased at compile time to "ezpublish_rest.session_authenticator" by the Security factory.
    ibexa.rest.security.authentication.listener.session:
        class: Ibexa\Rest\Server\Security\RestAuthenticator
        arguments:
            - "@security.token_storage"
            - "@security.authentication.manager"
            - ~ # Will be replaced at compile time by security provider key
            - "@event_dispatcher"
            - '@ibexa.config.resolver'
            - "@?logger"
        abstract: true

    Ibexa\Contracts\Rest\Security\AuthorizationHeaderRESTRequestMatcher: ~

    Ibexa\Rest\Server\Security\RestLogoutHandler:
        arguments:
            - '@ibexa.config.resolver'

    Ibexa\Rest\Server\Security\CsrfTokenManager:
        arguments:
            - '@?security.csrf.token_generator'
            - '@?security.csrf.token_storage'
            - '@?request_stack'

    Ibexa\Rest\Server\Security\EventListener\SecurityListener:
        arguments:
            - '@Ibexa\Contracts\Core\Repository\PermissionResolver'
        tags:
            - { name: kernel.event_subscriber }
