parameters:
    ibexa.rest.authorization_header_name: ~

services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    Ibexa\Contracts\Rest\Security\AuthorizationHeaderRESTRequestMatcher:
        arguments:
            $headerName: '%ibexa.rest.authorization_header_name%'

    Ibexa\Rest\Server\Security\CsrfTokenManager:
        arguments:
            - '@?security.csrf.token_generator'
            - '@?security.csrf.token_storage'
            - '@?request_stack'

    Ibexa\Rest\Server\Security\EventListener\JWTAuthenticationSuccessSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\Rest\Security\Authenticator\RestAuthenticator: ~
