schemas:
    BaseObject:
        type: object
        required:
            - _media-type
        properties:
            _media-type:
                xml:
                    attribute: true
                type: string
            _href:
                xml:
                    attribute: true
                type: string
